### ISSUE TITLE
Salvando o documento oficial em outro link

### ISSUE THREAD

**Issue by edusantana** [gustavofbreunig/abntex2unijui#1]
O link do documento original parece um pouco... não definitivo.

Estou fazendo esse issue para salvar o documento em um local mais definitivo, caso o original sai do ar.

- [TRABALHOS ACADEMICOS 85-2016-UNIJUI.pdf](https://github.com/gustavofbreunig/abntex2unijui/files/1081810/TRABALHOS.ACADEMICOS.85-2016-UNIJUI.pdf)

**Comment by gustavofbreunig** [comment]
@edusantana , na verdade é o link que a universidade considera como definitivo, até mesmo na página de perguntas frequentes da biblioteca (https://www.unijui.edu.br/biblioteca/duvidas-frequentes). Leia a primeira pergunta, quanto à norma ABNT.

Também é o link passado pelos professores aos alunos.

**Comment by edusantana** [comment]
Eu entendo, esse é o **link oficial**. Mas pode ser que ele mude nos próximo dez anos... então, com o link alternativo ficamos resguardados :+1: 

Obrigado pela contribuição.
